# Generated by Django 3.2.5 on 2021-07-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210725_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='desp', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(default='images/dlogo.jpeg', upload_to='images'),
        ),
    ]
